export enum DetailText {
    Title = "Title",
    Year = "Release year",
    Rated = "Age rating",
    Released = "Release date",
    Runtime = "Runtime",
    Genre = "Genre",
    Director = "Director",
    Writer = "Writer",
    Actors = "Actors",
    Plot = "Plot",
    Language = "Language",
    Country = "Country",
    Awards = "Awards",
    Poster = "Poster",
    Ratings = "Ratings",
    Metascore = "Metascore",
    imdbRating = "Rating by Imdb",
    imdbVotes = "Votes by Imdb",
    imdbID = "id",
    Type = "Type",
    totalSeasons = "Number of season",
    DVD = "DVD Release date",
    BoxOffice = "Box office",
    Production = "Production",
    Website = "Website",
}